// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 The PharosVPN Authors

// api.js wraps the Wails-generated Go bindings (frontend/wailsjs/go/main/App.js)
// and runtime events (frontend/wailsjs/runtime/runtime.js). Those files are
// generated by `wails dev` / `wails build` from the bound App struct in app.go;
// they do not exist in source control (see frontend/wailsjs/.gitkeep). Importing
// through this single module keeps every component decoupled from the generated
// paths and lets the app no-op gracefully when opened in a plain browser (no
// Wails runtime), which is handy for pure-UI iteration.

import * as App from '../../wailsjs/go/main/App.js';
import { EventsOn } from '../../wailsjs/runtime/runtime.js';

export const api = {
	listProfiles: () => App.ListProfiles(),
	getState: () => App.GetState(),
	getCloudInfo: () => App.GetCloudInfo(),
	getMap: (id, connected) => App.GetMap(id, connected),
	connect: (id, proto, password) => App.Connect(id, proto, password || ''),
	disconnect: () => App.Disconnect(),
	importProfile: () => App.ImportProfile(),
	pickDeviceFile: () => App.PickDeviceFile(),
	syncFromController: (deviceFile, email, password) =>
		App.SyncFromController(deviceFile, email, password),
	syncNow: () => App.SyncNow(),
	logout: () => App.Logout(),
	setDisabled: (bundle, disabled) => App.SetDisabled(bundle, disabled),
	deleteProfile: (bundle) => App.DeleteProfile(bundle)
};

// on subscribes to a backend event ("state" | "cloud" | "profiles"). Returns an
// unsubscribe function.
export function on(event, handler) {
	return EventsOn(event, (...args) => handler(...args));
}

// humanBytes formats a byte count compactly (e.g. "1.2 MB"), matching the worker.
export function humanBytes(n) {
	if (n == null) return '0 B';
	if (n < 1024) return `${n} B`;
	const units = ['KB', 'MB', 'GB', 'TB', 'PB'];
	let x = n,
		i = -1;
	do {
		x /= 1024;
		i++;
	} while (x >= 1024 && i < units.length - 1);
	return `${x.toFixed(1)} ${units[i]}`;
}

// agoLabel renders an ISO timestamp as a compact "3m ago".
export function agoLabel(iso) {
	if (!iso) return null;
	const t = Date.parse(iso);
	if (Number.isNaN(t)) return null;
	const d = (Date.now() - t) / 1000;
	if (d < 60) return 'just now';
	if (d < 3600) return `${Math.floor(d / 60)}m ago`;
	if (d < 86400) return `${Math.floor(d / 3600)}h ago`;
	return `${Math.floor(d / 86400)}d ago`;
}
